// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordShop.Repository;

#nullable disable

namespace RecordShop.Migrations
{
    [DbContext(typeof(RecordShopDbContext))]
    [Migration("20250130221420_m2")]
    partial class m2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecordShop.Model.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("MusicGenre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            MusicGenre = "ROCK",
                            ReleaseYear = 1969,
                            Stock = 10,
                            Title = "Abbey Road"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            MusicGenre = "ROCK",
                            ReleaseYear = 1970,
                            Stock = 40,
                            Title = "Let It Be"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 2,
                            MusicGenre = "POP",
                            ReleaseYear = 2014,
                            Stock = 15,
                            Title = "1989"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 3,
                            MusicGenre = "POP",
                            ReleaseYear = 1982,
                            Stock = 10,
                            Title = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 2,
                            MusicGenre = "COUNTRY",
                            ReleaseYear = 2008,
                            Stock = 55,
                            Title = "Fearless"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 2,
                            MusicGenre = "CLASSICAL",
                            ReleaseYear = 2020,
                            Stock = 75,
                            Title = "Folklore"
                        });
                });

            modelBuilder.Entity("RecordShop.Model.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Legendary British rock band.",
                            Name = "The Beatles"
                        },
                        new
                        {
                            Id = 2,
                            About = "Award-winning pop and country music artist.",
                            Name = "Taylor Swift"
                        },
                        new
                        {
                            Id = 3,
                            About = "Known as the King of Pop, Michael Jackson was a global icon and music legend.",
                            Name = "Michael Jackson"
                        });
                });

            modelBuilder.Entity("RecordShop.Model.Album", b =>
                {
                    b.HasOne("RecordShop.Model.Artist", "AlbumArtist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlbumArtist");
                });

            modelBuilder.Entity("RecordShop.Model.Artist", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
